config/routes.rb
Rails.application.routes.draw do
  resources :privacypolicy, only: [:index]
  resources :termsofservice, only: [:index]
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  mount ActionCable.server => '/cable'
  
  
  resources :themes
  resources :rooms do
    	collection do
  	  get 'login'
  	  get 'list'
  	  put 'join'
  	  get 'room_out'
  	  put 'room_out_member'
  	  get 'judge'

  	end
  end
  
  resources :villages do
  	collection do
  	  get 'board'
  	  put 'create'
  	  get 'modal_trigger_show'
  	  put 'resend_show_village'
  	  put 'notif_result_village'
  	end
  end
  
  
  
  
  get 'selectroom/index'
  # get 'rule/index'
  resources :rule do
    collection do
  	  get 'rule_detail'
  	end
  end
  
  
  get 'welcome/index'
  
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<%= content_for(:body_index, "index") %>
<span id="disp_show_welcom">

<span class="notice"><%= notice %></span>
<span class="alert"><%= alert %></span>

<div class="out_relative">

<div class="resizeimage">
  <img src="/title.jpg">
</div>
</div><br><br>

<div class="outer" ontouchstart="">
<div class="out_relative">
  <div class="kadomaru inner" >
    始める
    <!--<%= link_to '', controller: rooms_path %>-->
    <!--<%= link_to '', login_rooms_path %>-->
    <%= link_to '', controller: :selectroom %>
    
  </div><br>
  <div class="kadomaru inner">
    ルール説明
    <%= link_to '', controller: :rule %>
    <!--<%= link_to '', rule_detail_rule_index_path %>-->
  </div>
</div>
  <br>
  <div class="outer">
    ©2020 オオメノルー　all rights reserved.<br><br></div>
<a rel="noopener sponsored" href="https://www.dlsite.com/maniax/dlaf/=/t/t/link/work/aid/whirlstorm/id/RJ258362.html" target="_blank"><img src="//img.dlsite.jp/modpub/images2/work/doujin/RJ259000/RJ258362_img_sam.jpg" alt="" border="0" class="target_type" /></a>
<a rel="noopener sponsored" href="https://www.dlsite.com/maniax/dlaf/=/t/t/link/work/aid/whirlstorm/id/RJ286012.html" target="_blank"><img src="//img.dlsite.jp/modpub/images2/work/doujin/RJ287000/RJ286012_img_sam.jpg" alt="" border="0" class="target_type" /></a>
<a rel="noopener sponsored" href="https://www.dlsite.com/maniax/dlaf/=/t/t/link/work/aid/whirlstorm/id/RJ271712.html" target="_blank"><img src="//img.dlsite.jp/modpub/images2/work/doujin/RJ272000/RJ271712_img_sam.jpg" alt="" border="0" class="target_type" /></a>
</div>
<br>