config/routes.rb
Rails.application.routes.draw do
  resources :privacypolicy, only: [:index]
  resources :termsofservice, only: [:index]
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  mount ActionCable.server => '/cable'
  
  
  resources :themes
  resources :rooms do
    	collection do
  	  get 'login'
  	  get 'list'
  	  put 'join'
  	  get 'room_out'
  	  put 'room_out_member'
  	  get 'judge'

  	end
  end
  
  resources :villages do
  	collection do
  	  get 'board'
  	  put 'create'
  	  get 'modal_trigger_show'
  	  put 'resend_show_village'
  	  put 'notif_result_village'
  	end
  end
  
  
  
  
  get 'selectroom/index'
  # get 'rule/index'
  resources :rule do
    collection do
  	  get 'rule_detail'
  	end
  end
  
  
  get 'welcome/index'
  
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/village.rb
class Village < ApplicationRecord

  def self.createVillageNum
    # villageNumのユニーク値算出
    max = Village.maximum(:villageNum)
    if max.nil?
    	villageNumOrd = 1
    else
    	villageNumOrd = max + 1
    end
    
    return villageNumOrd
  end

end

app/controllers/villages_controller.rb
class VillagesController < ApplicationController
  before_action :authenticate_user!

  def create
    logger.debug("Village#createに入りました")
    logger.debug(params)
    
    # 村テーブルメンテ　24h以上前の村を削除
    Village.where('created_at <= ?', 24.hour.ago).delete_all
    
    # villageNumのユニーク値算出
    villageNumOrd = Village.createVillageNum
    
    # お題　作成
    @theme = Theme.where( 'id >= ?', rand(Theme.first.id..Theme.last.id) ).first.content
    
    ## 村　配役構築
    # 村メンバー算出
    @showRoomNum,@showOwnName,@showMemberTxt,@showVilListAry,@showMemListAry,@showOwnData = Room.getRoomShowText(params[:roomNum].to_i)

    # 村作成条件　チェック  村１名、オーナーのみ、メンバー０名を許容するため、以下コード非対象
    # if @showMemberTxt.blank?
    #   logger.debug("メンバー０名で作成できず")
    #   # prm = "$('#modal_err_createVlg_lackmember').modal('show')"
    #   # render :js => prm
    #   # render "rooms/show"
      
    #   # pram2 = "window.location = '$('#modal_err_createVlg_lackmember').modal('show')'"
    #   # render :js => pram2
    #   #render js: "alert('Hello Rails');"
      
    #   # ChatChannel.broadcast_to('message', {"message"=>"err_createVlg_lackmember", "roomNum"=>params[:roomNum], "action"=>"err_createVlg_lackmember"})
    #   return
    # end
    
    # 村メンバー
    logger.debug("村メンバー：")
    logger.debug(@showVilListAry)

    # GM役、内通者役の配列番号　抽選
    max = @showVilListAry.count
    logger.debug("■村　人数： #{max}")

    
    gmnaituu = (0..(max-1)).to_a.sort_by{rand}
    logger.debug("■抽選用　gmnaituu： #{gmnaituu}")

    # 	４人     マイノリティ*１、他マジョリティ
    # 	５～６人   マイノリティ*１、ストーカー*１、他マジョリティ
    # 	７～１０人  マイノリティ*１、ストーカー*１、インフルエンサー*１、他マジョリティ
    # 	１１人以上  マイノリティ*１、ストーカー*２、インフルエンサー*１、他マジョリティ

    # 人数別配役　配置
    if max <= 1     # 	１人     マイノリティ　特殊な許容
      logger.debug("■村create 人数別配役　配置 一人用")
      rnd = rand(4)
      case rnd
      when 0
        position = "マイノリティ"
      when 1
        position = "ストーカー"
      when 2
        position = "インフルエンサー"
      else
        position = "マジョリティ"
      end
        
      @village = Village.new(roomNum: params[:roomNum] , villageNum: villageNumOrd , name: @showVilListAry[0][:name] , email: @showVilListAry[0][:email] , position: position , theme: @theme)
      @village.save

    elsif max <= 4     # 	４人     マイノリティ*１、他マジョリティ
      logger.debug("■村create 人数別配役　配置 ４人以下用")
      @showVilListAry.each_with_index do |village , i|
        # binding.pry
        if i == gmnaituu[0]
          position = "マイノリティ"
        else
          position = "マジョリティ"
        end
        @village = Village.new(roomNum: params[:roomNum] , villageNum: villageNumOrd , name: village[:name] , email: village[:email] , position: position , theme: @theme)
        @village.save
      end

    elsif max <= 6  # 	５～６人   マイノリティ*１、インフルエンサー*１、他マジョリティ
      logger.debug("■村create 人数別配役　配置 ６人以下用")
      @showVilListAry.each_with_index do |village , i|
        if i == gmnaituu[0]
          position = "マイノリティ"
        elsif i == gmnaituu[1] 
          position = "インフルエンサー"
        else
          position = "マジョリティ"
        end
        @village = Village.new(roomNum: params[:roomNum] , villageNum: villageNumOrd , name: village[:name] , email: village[:email] , position: position , theme: @theme)
        @village.save
      end

    elsif max <= 10 # 	７～１０人  マイノリティ*１、ストーカー*１、インフルエンサー*１、他マジョリティ
      logger.debug("■村create 人数別配役　配置 １０人以下用")
      @showVilListAry.each_with_index do |village , i|
        if i == gmnaituu[0]
          position = "マイノリティ"
        elsif i == gmnaituu[1] 
          position = "ストーカー"
        elsif i == gmnaituu[2] 
          position = "インフルエンサー"
        else
          position = "マジョリティ"
        end
        @village = Village.new(roomNum: params[:roomNum] , villageNum: villageNumOrd , name: village[:name] , email: village[:email] , position: position , theme: @theme)
        @village.save
      end

    else            # 	１１人以上  マイノリティ*１、ストーカー*２、インフルエンサー*１、他マジョリティ
      logger.debug("■村create 人数別配役　配置 １１人以上用")
      @showVilListAry.each_with_index do |village , i|
        if i == gmnaituu[0]
          position = "マイノリティ"
        elsif i == gmnaituu[1] 
          position = "ストーカー"
        elsif i == gmnaituu[2] 
          position = "ストーカー"
        elsif i == gmnaituu[3] 
          position = "インフルエンサー"
        else
          position = "マジョリティ"
        end
        @village = Village.new(roomNum: params[:roomNum] , villageNum: villageNumOrd , name: village[:name] , email: village[:email] , position: position , theme: @theme)
        @village.save
      end
    end

    ChatChannel.broadcast_to('message', {"message"=>"show_village", "roomNum"=>params[:roomNum], "villageNum"=> villageNumOrd ,"action"=>"show_village"})

    list = Village.where(villageNum: villageNumOrd)
    list.each do |member|
      logger.debug("■村　配役： #{member.name}  #{member.position}") 
    end

    redirect_to @village
  end





  def board
    logger.debug("Villages#boardに入りました")
    logger.debug(params)
    
    @village = Village.find(params[:id])
    @theme   = @village.theme

    @room = Room.where(email: current_user.email).where(roomNum: @village.roomNum)[0]
    
    # 自身のvillage情報に上書き
    @village = Village.where(villageNum: @village.villageNum).where(email: current_user.email)[0]
  end
  

  def show
    # params villageNum: villageNumOrd , roomNum: params[:roomNum]
    logger.debug("Village#showに入りました")
    logger.debug(params)
    
    @village = Village.find(params[:id])
    @theme   = @village.theme

    @room = Room.where(email: current_user.email).where(roomNum: @village.roomNum)[0]
    
    # 自身のvillage情報に上書き
    @village = Village.where(villageNum: @village.villageNum).where(email: current_user.email)[0]
    
    logger.debug("役職： #{@village.position}")
  end

  def index
    logger.debug("Villages#indexに入りました")
    
    # お題　作成
    @theme = Theme.where( 'id >= ?', rand(Theme.first.id..Theme.last.id) ).first.content
    
  end

  def modal_trigger_show
    logger.debug("Village#modal_trigger_showに入りました")
    logger.debug(params)

    # redirect_to action: 'show' , villageNum: params[:villageNum].to_i , roomNum: params[:roomNum].to_i
    pram1 = '?villageNum=' + params[:villageNum] + '&roomNum=' + params[:roomNum] + '\''
    # pram2 = "window.location = '/villages/show" +  pram
    pram2 = Village.where(villageNum: params[:villageNum])[0].id.to_s +  pram1
    pram3 = "window.location = '/villages/" + pram2
    
    logger.debug("pram1: #{pram1}")
    logger.debug("pram2: #{pram2}")
    logger.debug("pram3: #{pram3}")

    render :js => pram3
    
  end

  # 村開始時に、部屋画面にいなかったメンバーへの再送通知（村開始）
  def resend_show_village
    logger.debug("Village#resend_show_villageに入りました")
    logger.debug(params)
  
    ChatChannel.broadcast_to('message', {"message"=>"show_village", "roomNum"=>params[:roomNum], "villageNum"=> params[:villageNum] ,"action"=>"show_village"})

  end
  
  # ゲーム結果を全員に通知する
  def notif_result_village
    logger.debug("Village#notif_result_villageに入りました")
    logger.debug(params)

    # マイノリティは一人のみ
    @village = Village.where(villageNum: params[:villageNum].to_i).where(position: "マイノリティ").first
    msg = "<h1>マイノリティ：#{@village.name}<br>"
    
    # ストーカーは複数人の可能性あり
    list = Village.where(villageNum: params[:villageNum].to_i).where(position: "ストーカー")
    list.each do |member|
      msg = msg + "<h1>ストーカー：#{member.name}<br>"
    end
    
    # インフルエンサーも複数対応
    list = Village.where(villageNum: params[:villageNum].to_i).where(position: "インフルエンサー")
    list.each do |member|
      msg = msg + "<h1>インフルエンサー：#{member.name}<br>"
    end

    ChatChannel.broadcast_to('message', {"message"=>"notif_result", "roomNum"=>params[:roomNum], "villageNum"=> params[:villageNum],"resultMsg"=>msg})

  end
  
  

end

app/helpers/villages_helper.rb
module VillagesHelper
end

app/views/villages/_index.html.erb
<%= content_for(:body_index, "index") %>

<div class="outer" ontouchstart="">
  <div class="out_relative">

    <div class="title_small">
      <img src="/logo_data_01.jpg">
    </div><br>
    <div class="kadomaru_futinasi inner">
      お題
    </div>
    <div class="posi_type"><%= @theme %></div><br>

    <div class="kadomaru_futinasi inner">
      あなたの役職
    </div>

    <div class="title_small">
      <img src="/minority_no.png">
    </div><br>
    <div class="posi_type">あなたは少数派！</div><br>
    最多得票で追放されない事を目指す。<br>
    お題の「ベストアンサー」を想像して、
    少し離れた回答を書こう。<br><br>


    <div class="kadomaru inner">
      ホワイトボード
      <%= link_to '', board_villages_path %>
      <!--<a href="board.html"></a>-->
    </div><br>
    <div class="kadomaru inner">
      戻る
      <%= link_to '', controller: rooms_path %>
      <!--<a href="room.html"></a>-->
    </div><br><br>

  </div><br><br>
</div>

app/views/villages/board.html.erb
<%= content_for(:body_index, "index") %>
<span id="disp_show_board">
<span id="datatag" data-roomnum= <%= @room.roomNum %> data-villagenum=<%= @village.villageNum %> data-position= <%= @room.position %> data-resultmsg="" ></span> 

<div class="outert">
  <div class="out_relative ">
    <span style="font-size: 28vw">
    <div class="fulldisp">
      <img src="/white_board.png">
    </div>
    <div class="backicon">
      戻る
      <%= link_to '', village_path(id: @village.id) %>
    </div>
    
    <textarea id="textarea_board" class="box_textarea" rows="1" placeholder="ここへ"></textarea></span>
    

  </div>
</div>

<%= javascript_include_tag "board.js" %>

<!-- モーダル -->
<!-- ゲーム終了通知 -->
<div class="modal fade" id="modal_notif_result" tabindex="-1" data-backdrop="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">ゲームの終了通知</h4>
      </div>
      <div class="modal-body">
        
      </div>
      <div class="modal-footer">
        <button type="button" id="modal_btn_start_vil" class="btn btn-warning" data-dismiss="modal">OK</button>
      </div>
    </div>
  </div>
</div>

app/views/villages/index.html.erb
<%= content_for(:body_index, "index") %>

<div class="outer" ontouchstart="">
  <div class="out_relative">

    <div class="title_small">
      <img src="/logo_data_01.jpg">
    </div><br>
    <div class="kadomaru_futinasi inner">
      お題
    </div>
    <div class="posi_type"><%= @theme %></div><br>

    <div class="kadomaru_futinasi inner">
      あなたの役職
    </div>

    <div class="title_small">
      <img src="/minority_no.png">
    </div><br>
    <div class="posi_type">あなたは少数派！</div><br>
    最多得票で追放されない事を目指す。<br>
    お題の「ベストアンサー」を想像して、
    少し離れた回答を書こう。<br><br>


    <div class="kadomaru inner">
      ホワイトボード
      <%= link_to '', board_villages_path %>
      <!--<a href="board.html"></a>-->
    </div><br>
    <div class="kadomaru inner">
      戻る
      <%= link_to '', controller: rooms_path %>
      <!--<a href="room.html"></a>-->
    </div><br><br>

  </div><br><br>
</div>

app/views/villages/show.html.erb
<%= content_for(:body_index, "index") %>
<span id="disp_show_village">
<span id="datatag" data-roomnum= <%= @room.roomNum %> data-villagenum=<%= @village.villageNum %> data-position= <%= @room.position %> data-resultmsg="" ></span> 

<div class="outer" ontouchstart="">
  <div class="out_relative">

    <div class="title_small">
      <img src="/logo_data_01.jpg">
    </div><br>
    ルームID:<%= @room.roomNum %><br>
    <div class="kadomaru_futinasi inner">
      お題
    </div>
    <div class="posi_type"><%= simple_format(@theme) %></div><br>

    <div class="kadomaru_futinasi inner">
      あなたの役職
    </div><br>


    <% if @village.position == 'マイノリティ' %>
      <div class="title_small">
        <img src="/minority_no.png">
      </div><br>
      <div class="posi_type">あなたは少数派！</div><br>
      最多得票で追放されない事を目指す。<br>
      お題の「ベストアンサー」を想像して、<br>
      少し離れた回答を書こう。<br><br>

    <% elsif @village.position == 'ストーカー' %>
      <div class="title_small">
        <img src="/stalker_no.png">
      </div><br>
      <div class="posi_type">あなたはマイノリティーが<br>大好き！</div><br>
      マイノリティーと同じ回答を書こう。<br>
      ※どんな状況でもマイノリティーと<br>
      同じ回答なら勝利<br><br>

    <% elsif @village.position == 'インフルエンサー' %>
      <div class="title_small">
        <img src="/influencer_no.png">
      </div><br>
      <div class="posi_type">あなたは目立ちたがり屋！</div><br>
      とにかく注目されよう。<br>
      投票時にたくさん票をもらうために<br>
      「ベストアンサー」とは<br>
      ほど遠い回答を書こう。<br><br>

    <% else # マジョリティ%>  
      <div class="title_small">
        <img src="/majority_no.png">
      </div><br>
      <div class="posi_type">あなたは多数派！</div><br>
      「ベストアンサー」を目指す。<br>
      お題に沿った素直な回答や、<br>
      なるべく被りそうな回答を書こう。<br><br>

    <% end %>


    <div class="kadomaru inner">
      ホワイトボード
      <%= link_to '', board_villages_path(id: @village.id) %>
      <!--<a href="board.html"></a>-->
    </div><br>
    <% if @room.position == 'owner' %>
      <div class="kadomaru inner" ontouchstart="">
        役職を再送する
        <%= link_to '' , resend_show_village_villages_path(roomNum: @room.roomNum , villageNum: @village.villageNum) ,method: :put , :remote => true %>
        <!--<a href="room.html"></a>-->
      </div><br>
      <div class="kadomaru inner" ontouchstart="">
        結果を全員に通知
        <%= link_to '' , notif_result_village_villages_path(roomNum: @room.roomNum , villageNum: @village.villageNum) ,method: :put , :remote => true ,data: { confirm: '全員に結果（正体）を通知します。OK?' } %>
        <!--<a href="room.html"></a>-->
      </div><br>
    <% end %>
    <div class="kadomaru inner" ontouchstart="">
      部屋に戻る
      <%= link_to '' , join_rooms_path(roomNum: @room.roomNum , name:current_user.name , email: current_user.email) ,method: :put ,data: { confirm: '部屋に戻ります。OK?' } %>
      <!--<a href="room.html"></a>-->
    </div><br><br>
</div><br><br>
</div>


<!-- モーダル -->
<!-- ゲーム終了通知 -->
<div class="modal fade" id="modal_notif_result" tabindex="-1" data-backdrop="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">ゲームの終了通知</h4>
      </div>
      <div class="modal-body">
        
      </div>
      <div class="modal-footer">
        <button type="button" id="modal_btn_start_vil" class="btn btn-warning" data-dismiss="modal">OK</button>
      </div>
    </div>
  </div>
</div>