config/routes.rb
Rails.application.routes.draw do
  resources :privacypolicy, only: [:index]
  resources :termsofservice, only: [:index]
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  mount ActionCable.server => '/cable'
  
  
  resources :themes
  resources :rooms do
    	collection do
  	  get 'login'
  	  get 'list'
  	  put 'join'
  	  get 'room_out'
  	  put 'room_out_member'
  	  get 'judge'

  	end
  end
  
  resources :villages do
  	collection do
  	  get 'board'
  	  put 'create'
  	  get 'modal_trigger_show'
  	  put 'resend_show_village'
  	  put 'notif_result_village'
  	end
  end
  
  
  
  
  get 'selectroom/index'
  # get 'rule/index'
  resources :rule do
    collection do
  	  get 'rule_detail'
  	end
  end
  
  
  get 'welcome/index'
  
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord

  def self.createRoomNum
    # roomNumのユニーク値算出
    max = Room.maximum(:roomNum)
    if max.nil?
    	roomNumOrd = 1
    else
    	roomNumOrd = max + 1
    end
    
    return roomNumOrd
  end
  

  # 表示向けデータ作成(一覧)
  def self.getRoomIndexText
    # return @roomNumSorted[] , @ownNameSorted[] , @memberTxtSorted[]
    
    @rooms = self.all
      
  	@roomNum = []
  	@ownName = []
  	@memberTxt = []

  	@rooms.each do |room|
  		if room.position == "owner"
  		  @roomNum.push(room.roomNum)
  		  @ownName.push(room.name)
  		  @memberTxt.push(nil)
  		end
  	end

  	@rooms.each do |room|
      if room.position == "member"
      
        # エラーケースへの自浄行動
        if @roomNum.index(room.roomNum).nil?
          logger.debug("★★エラー！！！memberは存在するが、ownerが存在しない　自浄作業が必要な状況")
          Room.where(id: room.id).delete_all
        else
          index = @roomNum.index(room.roomNum)
          # logger.debug("room.id=#{room.id}")
          # logger.debug("index=#{index}")
          # logger.debug("@memberTxt=#{@memberTxt}")
          
          if @memberTxt[index] == nil
            @memberTxt[index] = room.name
          else
            @memberTxt[index] = @memberTxt[index] + "," + room.name
          end  		    
          
        end
      end
  	end
  	
  	logger.debug("@roomNum = #{@roomNum}")
  	logger.debug("@ownName = #{@ownName}")
  	logger.debug("@memberTxt = #{@memberTxt}")
    	
    #　配列順序　降順へ
    @roomNumSorted = @roomNum.sort.reverse!
    @roomNumSortedIndex = []
    @ownNameSorted = []
    @memberTxtSorted = []
    
    @roomNumSorted.each do |num|
    	@roomNum.each_with_index do |target , i|
    		if target == num
    			@roomNumSortedIndex.push(i)
    		end
    	end
    end
    
    # puts "@roomNum: #{@roomNum}"
    # puts "@roomNumSorted: #{@roomNumSorted}"
    # puts "@roomNumSortedIndex: #{@roomNumSortedIndex}"
    
    @roomNumSortedIndex.each do |index|
        @ownNameSorted.push(@ownName[index])
        @memberTxtSorted.push(@memberTxt[index])
    end
    
    # puts "@roomNumSorted: #{@roomNumSorted}"
    # puts "@ownNameSorted: #{@ownNameSorted}"
    # puts "@memberTxtSorted: #{@memberTxtSorted}"


  	return @roomNumSorted , @ownNameSorted , @memberTxtSorted
      
  end

  # 表示向けデータ作成(部屋個別)
  def self.getRoomShowText(roomNum)
    # return @showRoomNum,@showOwnName,@showMemberTxt[],@showVilList[],@showMemList[],@showOwnData

    @rooms = self.where(roomNum: roomNum)
      
  	@showRoomNum = ""
  	@showOwnName = ""
  	@showMemberTxt = []
  	@showVilList = []
  	@showMemList = []
  	@showOwnData = ""

  	@rooms.each do |room|
  		if room.position == "owner"
  		  @showRoomNum = room.roomNum
  		  @showOwnName = room.name
  		  @showOwnData = { name: room.name, email: room.email}
  		else # memberの場合
  		  @showMemberTxt.push(room.name)
  		  @showMemList.push({ name: room.name, email: room.email})
  		end
  		@showVilList.push({ name: room.name, email: room.email})
  	end

    return @showRoomNum,@showOwnName,@showMemberTxt,@showVilList,@showMemList,@showOwnData
  end
  
  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def create
    logger.debug("createに入りました")
    logger.debug(params)

    # 過去に自分がオーナーの部屋を削除
    if Room.where(position: "owner").where(email: params[:email]).exists?
      logger.debug("過去に自分がオーナーの部屋を削除しました")
      @room = Room.where(position: "owner").where(email: params[:email])[0]
      @brcst_roomNum = @room.roomNum.to_s # バッチ処理のため、外部変数が必要
      @brcst_name = @room.name            # バッチ処理のため、外部変数が必要
      @brcst_email = @room.email            # バッチ処理のため、外部変数が必要
      
      ChatChannel.broadcast_to('message', {"message"=>"room_controlle_close", "roomNum"=>@brcst_roomNum, "name"=>@brcst_name,  "action"=>"logout_room"})
      
      Room.where(roomNum: @room.roomNum).delete_all
    end

  	@room = Room.new(email:params[:email],name:params[:name],position:"owner",roomNum: Room.createRoomNum)
  	@room.save
  	redirect_to @room
  end




  def index
    # roomDBの異常値チェック
    # roomNum:Nilがあった場合は削除
    Room.where(roomNum: nil).delete_all

    @roomNum = []
    @ownName = []
    @memberTxt = []
    
    @roomNum,@ownName,@memberTxt = Room.getRoomIndexText

  end
  
  def join
    logger.debug("joinに入りました")
    logger.debug(params)
    
    # 参加した部屋がない場合
    if Room.where(roomNum: params[:roomNum]).blank?
      redirect_to action: 'index'
      return
    end
    
    
    # 存在しない場合は、追加する
    if Room.where(email: params[:email]).where(roomNum: params[:roomNum]).blank?
      @room = Room.new(name: params[:name],email: params[:email],position:"member",roomNum: params[:roomNum])
      
    	@room.save
    else # すでに存在する場合は追加しない
      @roomTmp = Room.where(email: params[:email]).where(roomNum: params[:roomNum])
      @room = @roomTmp[0]
    end
    
    if @room.position == "member"
      ChatChannel.broadcast_to('message', {"message"=>"room_controlle_join", "roomNum"=>params[:roomNum], "name"=>params[:name], "email"=>params[:email], "action"=>"join_room"})
    end
    
  	redirect_to @room
  end


    

  def show
    logger.debug("rooms#showに入りました")
    logger.debug(params)
    
    @room = Room.find(params[:id])

    @showRoomNum,@showOwnName,@showMemberTxtAry,@showVilListAry,@showMemListAry,@showOwnData = Room.getRoomShowText(@room.roomNum)
    @vilListCnt = @showVilListAry.count
    
    logger.debug("@showMemberTxtAry:#{@showMemberTxtAry}")
    logger.debug("@showVilListAry:#{@showVilListAry}")
    logger.debug("@showMemListAry:#{@showMemListAry}")
    logger.debug("@showOwnData:#{@showOwnData}")
    logger.debug(@showOwnData[:name])

  end

  def room_out
    logger.debug("rooms#room_outに入りました")
    logger.debug(params)
    
    if Room.where(id: params[:roomId]).empty?
      # nilの時は、なにも処理しない
    else
      @room = Room.find(params[:roomId])
      @brcst_roomNum = @room.roomNum.to_s # バッチ処理のため、外部変数が必要
      @brcst_name = @room.name            # バッチ処理のため、外部変数が必要
      @brcst_email = @room.email            # バッチ処理のため、外部変数が必要
      
      if @room.position == 'owner'
        ChatChannel.broadcast_to('message', {"message"=>"room_controlle_close", "roomNum"=>@brcst_roomNum, "name"=>@brcst_name,  "action"=>"logout_room"})
      else
        ChatChannel.broadcast_to('message', {"message"=>"room_controlle_logout", "roomNum"=>@brcst_roomNum, "name"=>@brcst_name, "email"=>@brcst_email, "action"=>"logout_room"})
      end
      
      Room.where(id: params[:roomId]).delete_all
    end
    
    redirect_to action: 'index'
  end

  def room_out_member
    logger.debug("rooms#room_out_memberに入りました")
    logger.debug(params)
    
    if Room.where(roomNum: params[:roomNum]).where(email: params[:email]).empty?
      # nilの時は、なにも処理しない
    else
      @room = Room.where(roomNum: params[:roomNum]).where(email: params[:email])[0]
      @brcst_roomNum = @room.roomNum.to_s # バッチ処理のため、外部変数が必要
      @brcst_name = @room.name            # バッチ処理のため、外部変数が必要
      @brcst_email = @room.email            # バッチ処理のため、外部変数が必要
      
      ChatChannel.broadcast_to('message', {"message"=>"room_controlle_logout", "roomNum"=>@brcst_roomNum, "name"=>@brcst_name, "email"=>@brcst_email, "action"=>"logout_room"})

      Room.where(email: params[:email]).delete_all
    end
  end
  






    
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_delete_list.html.erb
<%= content_for(:body_index, "index") %>



<div class="outer" ontouchstart="">
  <div class="out_relative">
    <div class="title_small">
      <img src="/logo_data_01.jpg">
    </div><br>
    <div class="kadomaru_red_futinasi inner">
        部屋一覧
        <%= link_to '', controller: rooms_path %>
    </div><br>
    
    <table class='table table-striped table-hover tbl_font'>
      <tr>
        <th class='id uesita'>ID</th>
        <th class='owner2 uesita'>オーナー</th>
        <th class='uesita'>メンバー</th>
      </tr>
      <tr>
        <td><%= link_to '1' , controller: rooms_path %></td>
        <td><%= link_to '孫悟空' , controller: rooms_path %></td>
  			<td><%= link_to 'ベジータ,ブルマ,トランクス,ヤムチャ' , controller: rooms_path %></td>
      </tr>
      <tr>
        <td><%= link_to '2' , controller: rooms_path %></td>
        <td><%= link_to 'ギニュー' , controller: rooms_path %></td>
  			<td><%= link_to 'グルド,バータ' , controller: rooms_path %></td>
      </tr>
      <tr>
        <td><%= link_to '3' , controller: rooms_path %></td>
        <td><%= link_to 'フリーザ' , controller: rooms_path %></td>
  			<td><%= link_to 'ドドリア、ザーボン' , controller: rooms_path %></td>
      </tr>
      <tr>
        <td><%= link_to '4' , controller: rooms_path %></td>
        <td><%= link_to 'ピラフ' , controller: rooms_path %></td>
  			<td><%= link_to 'シュウ、マイ' , controller: rooms_path %></td>
      </tr>
      <tr>
        <td><%= link_to '5' , controller: rooms_path %></td>
        <td><%= link_to 'レッド総帥' , controller: rooms_path %></td>
  			<td><%= link_to 'クマ、ムラサキ曹長、人造人間8号' , controller: rooms_path %></td>
      </tr>
      <tr>
        <td><%= link_to '6' , controller: rooms_path %></td>
        <td><%= link_to '亀仙人' , controller: rooms_path %></td>
  			<td><%= link_to 'ウーロン、プーアル、ランチ、チチ、牛魔王、ウミガメ、占いババ、閻魔大王' , controller: rooms_path %></td>
      </tr>


    </table>
    <br>

    <div class="kadomaru inner">
        部屋新規作成
        <%= link_to '', controller: rooms_path %>
    </div><br>
    
    <div class="kadomaru inner">
        戻る
        <%= link_to '', controller: :selectroom %>
    </div><br>
  </div>
</div>

app/views/rooms/_delete_yotei_login.html.erb
<%= content_for(:body_index, "index") %>

<div class="outer">
    <div class="out_relative">

      <div class="title_small">
        <img src="/logo_data_01.jpg">
      </div><br>
      <div class="kadomaru_red_futinasi inner">
          ログイン
        </div><br><br>
      <div class="col">
        <a href="rule.html" class="btn btn-twitter btn-xxl">
          <i class="fab fa-twitter fa-2x"></i>　Twitterでログインする
        </a>
      </div><br>

      <p class="border_text">または</p>   
      <br>
      <div class="col">
        <%= form_tag(selectroom_index_path,method: :get) do %>
          <div class="form-group">
            <%= label_tag :名前 %>
            <%= text_field_tag :class=>"form-control" %>
          </div>

          <%= submit_tag '一時アカウントでログイン', :class=>"kadomaru_futinasi_pit_prim inner" %>
          
        <% end %>

    </div><br><br>
  </div>
</div>

  

app/views/rooms/index.html.erb
<%= content_for(:body_index, "index") %>
<span id="disp_index_room">

<div class="outer" ontouchstart="">
  <div class="out_relative">
    <div class="title_small">
      <img src="/logo_data_01.jpg">
    </div><br>
    <div class="kadomaru_red_futinasi inner">
        部屋一覧
    </div><br>
    
    <table class='table table-striped table-hover tbl_font'>
      <tr>
        <th class='id uesita'>ID</th>
        <th class='owner2 uesita'>オーナー</th>
        <th class='uesita'>メンバー</th>
      </tr>
      <% for i in 0..((@roomNum.count) -1) do %>
        <tr>
          <td><%= link_to @roomNum[i] ,   join_rooms_path(roomNum: @roomNum[i] , name: current_user.name , email: current_user.email) ,method: :put %></td>
          <td><%= link_to @ownName[i] ,   join_rooms_path(roomNum: @roomNum[i] , name: current_user.name , email: current_user.email) ,method: :put %></td>
    
          <% if @memberTxt[i].nil? %>
            <td><%= link_to '　' , join_rooms_path(roomNum: @roomNum[i] , name: current_user.name , email: current_user.email) ,method: :put %></td>
          <% else %>
            <td><%= link_to @memberTxt[i] , join_rooms_path(roomNum: @roomNum[i] , name: current_user.name , email: current_user.email) ,method: :put %></td>
          <% end %>
          
        </tr>
      <% end %>

    </table>
    <br>

    <div class="kadomaru inner">
        部屋新規作成
        <%= link_to '', rooms_path(email: current_user.email , name: current_user.name ,position:'owner') , method: :post %>
    </div><br>
    
    <div class="kadomaru inner">
        戻る
        <%= link_to '', controller: :selectroom %>
    </div><br>
  </div>
  <div class="outer">
    ©2020 オオメノルー　all rights reserved.<br><br></div>
  <a rel="noopener sponsored" href="https://www.dlsite.com/maniax/dlaf/=/t/t/link/work/aid/whirlstorm/id/RJ258362.html" target="_blank"><img src="//img.dlsite.jp/modpub/images2/work/doujin/RJ259000/RJ258362_img_sam.jpg" alt="" border="0" class="target_type" /></a>
  <a rel="noopener sponsored" href="https://www.dlsite.com/maniax/dlaf/=/t/t/link/work/aid/whirlstorm/id/RJ286012.html" target="_blank"><img src="//img.dlsite.jp/modpub/images2/work/doujin/RJ287000/RJ286012_img_sam.jpg" alt="" border="0" class="target_type" /></a>
  <a rel="noopener sponsored" href="https://www.dlsite.com/maniax/dlaf/=/t/t/link/work/aid/whirlstorm/id/RJ271712.html" target="_blank"><img src="//img.dlsite.jp/modpub/images2/work/doujin/RJ272000/RJ271712_img_sam.jpg" alt="" border="0" class="target_type" /></a>
</div>

<script type="text/javascript">blogparts={"base":"https://www.dlsite.com/","type":"product","site":"maniax","query":{"keyword_work_name":"RJ258362|RJ286012|RJ271712|RJ280378","ana_flg":"all"},"title":"指定作品","display":"horizontal","detail":"0","column":"v","image":"large","count":"3","wrapper":"0","autorotate":true,"aid":"whirlstorm"}</script><script type="text/javascript" src="https://www.dlsite.com/js/blogparts.js" charset="UTF-8"></script>

app/views/rooms/list.html.erb
<%= content_for(:body_index, "index") %>



<div class="outer" ontouchstart="">
  <div class="out_relative">
    <div class="title_small">
      <img src="/logo_data_01.jpg">
    </div><br>
    <div class="kadomaru_red_futinasi inner">
        部屋一覧
        <%= link_to '', controller: rooms_path %>
    </div><br>
    
    <table class='table table-striped table-hover tbl_font'>
      <tr>
        <th class='id uesita'>ID</th>
        <th class='owner2 uesita'>オーナー</th>
        <th class='uesita'>メンバー</th>
      </tr>
      <tr>
        <td><%= link_to '1' , controller: rooms_path %></td>
        <td><%= link_to '孫悟空' , controller: rooms_path %></td>
  			<td><%= link_to 'ベジータ,ブルマ,トランクス,ヤムチャ' , controller: rooms_path %></td>
      </tr>
      <tr>
        <td><%= link_to '2' , controller: rooms_path %></td>
        <td><%= link_to 'ギニュー' , controller: rooms_path %></td>
  			<td><%= link_to 'グルド,バータ' , controller: rooms_path %></td>
      </tr>
      <tr>
        <td><%= link_to '3' , controller: rooms_path %></td>
        <td><%= link_to 'フリーザ' , controller: rooms_path %></td>
  			<td><%= link_to 'ドドリア、ザーボン' , controller: rooms_path %></td>
      </tr>
      <tr>
        <td><%= link_to '4' , controller: rooms_path %></td>
        <td><%= link_to 'ピラフ' , controller: rooms_path %></td>
  			<td><%= link_to 'シュウ、マイ' , controller: rooms_path %></td>
      </tr>
      <tr>
        <td><%= link_to '5' , controller: rooms_path %></td>
        <td><%= link_to 'レッド総帥' , controller: rooms_path %></td>
  			<td><%= link_to 'クマ、ムラサキ曹長、人造人間8号' , controller: rooms_path %></td>
      </tr>
      <tr>
        <td><%= link_to '6' , controller: rooms_path %></td>
        <td><%= link_to '亀仙人' , controller: rooms_path %></td>
  			<td><%= link_to 'ウーロン、プーアル、ランチ、チチ、牛魔王、ウミガメ、占いババ、閻魔大王' , controller: rooms_path %></td>
      </tr>


    </table>
    <br>

    <div class="kadomaru inner">
        部屋新規作成
        <%= link_to '', controller: rooms_path %>
    </div><br>
    
    <div class="kadomaru inner">
        戻る
        <%= link_to '', controller: :selectroom %>
    </div><br>
  </div>
</div>

app/views/rooms/login.html.erb
<%= content_for(:body_index, "index") %>

<div class="outer">
    <div class="out_relative">

      <div class="title_small">
        <img src="/logo_data_01.jpg">
      </div><br>
      <div class="kadomaru_red_futinasi inner">
          ログイン
        </div><br><br>
      <div class="col">
        <a href="rule.html" class="btn btn-twitter btn-xxl">
          <i class="fab fa-twitter fa-2x"></i>　Twitterでログインする
        </a>
      </div><br>

      <p class="border_text">または</p>   
      <br>
      <div class="col">
        <%= form_tag(selectroom_index_path,method: :get) do %>
          <div class="form-group">
            <%= label_tag :名前 %>
            <%= text_field_tag :class=>"form-control" %>
          </div>

          <%= submit_tag '一時アカウントでログイン', :class=>"kadomaru_futinasi_pit_prim inner" %>
          
        <% end %>

    </div><br><br>
  </div>
</div>

  

app/views/rooms/show.html.erb
<%= content_for(:body_index, "index") %>

<span id="disp_show_room">
<span id="datatag" data-roomnum= <%= @room.roomNum %> data-villagenum=0 data-position= <%= @room.position %> data-resultmsg="" ></span> 


<div class="outer" ontouchstart="">
<div class="out_relative">
  <div class="title_small">
    <img src="/logo_data_01.jpg">
  </div>

  ルームID:<%= @room.roomNum %><br>
  <% if @room.position == 'owner' %>
    <div class="kadomaru_red_pit inner">
    ゲーム開始
    <%= link_to '', villages_path(roomNum: @room.roomNum ,name: @room.name ,roomId: @room.id ) , method: :put  ,:remote => true %>
    <!--<a href="villages.html"></a>-->
    </div><br><br>
  <% else %>
    あなたはメンバーです。<br>オーナーによるゲーム開始をお待ち下さい。<br><br>
  <% end %>


  <div class="kadomaru_futinasi inner">
    メンバー
  </div>
  <!--<div class="posi_type">７人</div>-->

  <p class="mem_list" id="show_room_mem">
    <span class="owner inner" id=<%= @showOwnData[:email]  %> ><%= @showOwnData[:name]  %></span>
    <% @showMemListAry.each do | member | %>
      <span class="member inner" id=<%= member[:email] %> >
        <%= member[:name] %>
        <% if @room.position == 'owner' %>
          <%= link_to '' , room_out_member_rooms_path(roomNum: @room.roomNum ,email: member[:email]) ,method: :put , :remote => true ,data: { confirm: 'メンバーを外します。OK?' } %>
        <% end %>
      </span>
    <% end %>
  </p>
  <span class="comment_sml">
    オーナーは赤色<br>
    <% if @room.position == 'owner' %>
      オーナーはメンバーをクリックして、外すことができます。
    <% end %>
  </span><br>
  

  <div class="kadomaru_futinasi inner">
    配役
  </div>
  <div class="posi_type" id="room_regu">
  <% if @vilListCnt <= 4 %>
    マイノリティー・・・１人<br>
    マジョリティー　・・残り<br>
  <% elsif @vilListCnt <= 6 %>
		マイノリティー・・・１人<br>
		インフルエンサー・・１人<br>
		マジョリティー　・・残り<br>
  <% elsif @vilListCnt <= 10 %>
		マイノリティー・・・１人<br>
		インフルエンサー・・１人<br>
		ストーカー・・・・・１人<br>
		マジョリティー　・・残り<br>
  <% else %>
		マイノリティー・・・１人<br>
		インフルエンサー・・１人<br>
		ストーカー・・・・・２人<br>
		マジョリティー　・・残り<br>
  <% end %>
  <span class="comment_sml">お題は、ゲーム開始時にランダムに選ばれます。</span>
  </div><br>

  <div class="kadomaru inner">
    部屋をぬける
    <%= link_to '' , room_out_rooms_path(roomId: @room.id ,email: @room.email)  ,data: { confirm: '部屋を抜けます。OK?' } %>
  </div><br><br>

</div><br><br>
</div>

<!-- モーダル・ダイアログ -->
<div class="modal fade" id="modal_close_room" tabindex="-1" data-backdrop="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        オーナーによって、部屋が閉じられました。「部屋一覧に戻る」ボタンを押して移動してください
      </div>
      <div class="modal-footer">
        <button type="button" id="modal_btn_close_room" class="btn btn-warning" onclick="location.href='../rooms'">部屋一覧に戻る</button>
      </div>
    </div>
  </div>
</div>


<div class="modal fade" id="modal_start_vil" tabindex="-1" data-backdrop="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        オーナーによって、役職が配布されました。「ゲームを始める」ボタンを押して遷移してください
      </div>
      <div class="modal-footer">
        <button type="button" id="modal_btn_start_vil" class="btn btn-warning">ゲームを始める</button>
      </div>
    </div>
  </div>
</div>


<script>
 $( function() {
  $('#modal_btn_start_vil').click( function () {
    $.ajax({
        url: '/villages/modal_trigger_show',
        type: 'GET',
        data: {roomNum: Number($('#datatag').data('roomnum')) , villageNum: Number($('#datatag').data('villagenum')) },
      });
  });
 });
</script>